env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - plugin:vue/recommended
  - prettier
globals:
  Vue: true
  _: true
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: { "vue/comment-directive": "off" }
